name: PR Pipeline
on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pipeline:
    strategy:
      matrix:
        os: ['ubuntu-slim']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.9.4
        with:
          pixi-version: v0.65.0
          cache: true
      - name: Run linter check
        run: pixi run lint-ci
      - name: Run all unit tests
        run: pixi run test
